site_name: GroovyScript

repo_name: CleanroomMC/GroovyScript-Docs
repo_url: https://github.com/CleanroomMC/GroovyScript-Docs

nav:
    - 'Groovy':
        - 'Introduction': 'groovy/introduction.md'
        - 'Builders': 'groovy/builder.md'
    - 'GroovyScript':
        - 'Mods':
            - 'EnderIO':
                - 'Alloy Smelter': 'groovyscript/mods/enderio/alloy_smelter.md'
                - 'SAG Mill': 'groovyscript/mods/enderio/sag_mill.md'
            - 'Mekanism':
                - 'Crusher': 'groovyscript/mods/mekanism/crusher.md'
        - 'Minecraft':
              - 'Crafting': 'groovyscript/minecraft/crafting.md'
    - 'Introduction': 'index.md'

theme:
    name: material
    palette:
        scheme: slate
    features:
        - content.code.annotate

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - attr_list
    - md_in_html